/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects and kept here so the
// checked-in skeleton type-checks before dependencies are installed.
